// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TitleExit","status":true,"description":"bbbbbbbbbb","parameters":{}},
{"name":"CGMZ_Core","status":true,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Show FPS Counter":"false","Fullscreen":"false","Simulate Production Env":"false","Force Locale":"","Fallback Locale":"en-US"}},
{"name":"CGMZ_TitleCommandWindow","status":true,"description":"标题选项拓展系统（为标题画面增加新的选项和美化）","parameters":{"Visible Commands":"4","Window Width":"30","Alignment":"center","Keep Original Commands":"true","Enable Text Codes":"true","Commands":"[]"}}
];
